# Generated by Django 4.1.1 on 2022-09-23 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=500)),
                ('caddress', models.CharField(max_length=250)),
                ('paddress', models.CharField(max_length=250)),
                ('dob', models.DateField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=1000)),
                ('foccu', models.CharField(max_length=1000)),
                ('fcontact', models.CharField(max_length=1000)),
                ('mother', models.CharField(default=0, max_length=1000)),
                ('moccu', models.CharField(default=0, max_length=1000)),
                ('mcontact', models.CharField(default=0, max_length=1000)),
                ('quali', models.CharField(max_length=250)),
                ('marks', models.IntegerField()),
                ('certificate', models.FileField(blank=True, max_length=250, null=True, upload_to='docx')),
                ('blood', models.CharField(max_length=250)),
                ('username', models.CharField(default=0, max_length=100)),
                ('password', models.CharField(default=0, max_length=150)),
                ('trans', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, max_length=250, null=True, upload_to='docx')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bno', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, max_length=250, null=True, upload_to='docx')),
                ('regno', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=250)),
                ('dphoto', models.ImageField(blank=True, max_length=250, null=True, upload_to='docx')),
                ('daddress', models.CharField(max_length=250)),
                ('dcontact', models.CharField(max_length=250)),
                ('demail', models.EmailField(max_length=250)),
                ('dlicesence', models.CharField(max_length=250)),
                ('accname', models.CharField(default=0, max_length=500)),
                ('accno', models.CharField(default=0, max_length=500)),
                ('ifsc', models.CharField(default=0, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Portions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('div', models.CharField(max_length=250)),
                ('sub1', models.CharField(max_length=250)),
                ('sub2', models.CharField(max_length=250)),
                ('sub3', models.CharField(max_length=250)),
                ('sub4', models.CharField(max_length=250)),
                ('sub5', models.CharField(max_length=250)),
                ('sub6', models.CharField(max_length=250)),
                ('sub7', models.CharField(max_length=250)),
                ('sub8', models.CharField(max_length=250)),
                ('sub9', models.CharField(max_length=250)),
                ('sub10', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=300)),
                ('desig', models.CharField(default=0, max_length=400)),
                ('contact', models.IntegerField()),
                ('photo', models.ImageField(upload_to='gallery')),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.TextField(max_length=50)),
                ('check1', models.TextField(default=0, max_length=250)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clgapp.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('place', models.CharField(max_length=250)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('guardian', models.CharField(max_length=1000)),
                ('school', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=1000)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(default=0, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='trans_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=250)),
                ('pickup', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
                ('guardname', models.CharField(max_length=250)),
                ('guardcontact', models.CharField(max_length=250)),
                ('bfee', models.IntegerField()),
                ('Staff_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clgapp.staff')),
                ('bus_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clgapp.bus')),
                ('driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clgapp.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Studymaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250, null=True)),
                ('pdfnote', models.ImageField(upload_to='media')),
                ('thumb', models.ImageField(blank=True, max_length=250, null=True, upload_to='media')),
                ('portions_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clgapp.portions')),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnum', models.CharField(default=0, max_length=250)),
                ('branchh', models.CharField(default=0, max_length=250)),
                ('sem', models.CharField(default=0, max_length=250)),
                ('subname', models.CharField(default=0, max_length=2000)),
                ('subcode', models.CharField(default=0, max_length=2000)),
                ('mark', models.CharField(default=0, max_length=2000)),
                ('grade', models.CharField(default=0, max_length=2000)),
                ('gpa', models.CharField(default=0, max_length=2000)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clgapp.admission')),
            ],
        ),
        migrations.CreateModel(
            name='Recorded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default=0, max_length=250)),
                ('sub', models.CharField(default=0, max_length=250)),
                ('thmb', models.ImageField(blank=True, max_length=250, null=True, upload_to='media')),
                ('url', models.URLField(default=0)),
                ('portions_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clgapp.portions')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(blank=True, max_length=240, null=True)),
                ('password', models.CharField(blank=True, max_length=240, null=True)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='design', to='clgapp.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Institute_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('contact', models.IntegerField()),
                ('desig', models.CharField(default=0, max_length=400)),
                ('image', models.ImageField(default=0, upload_to='gallery')),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clgapp.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Classonline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default=0, max_length=250)),
                ('date', models.DateField(default=0, max_length=250, null=True)),
                ('stime', models.TimeField(default=0, max_length=250)),
                ('etime', models.TimeField(default=0, max_length=250)),
                ('thumb', models.ImageField(blank=True, max_length=250, null=True, upload_to='media')),
                ('url', models.URLField(default=0)),
                ('status', models.CharField(default='True', max_length=250)),
                ('portions_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clgapp.portions')),
                ('staff_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clgapp.staff')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='Staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clgapp.staff'),
        ),
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clgapp.driver'),
        ),
        migrations.AddField(
            model_name='admission',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clgapp.designation'),
        ),
        migrations.AddField(
            model_name='admission',
            name='portion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clgapp.portions'),
        ),
    ]
